### PR TITLE
Add EthicHub Dapp in Valora

### PR DESCRIPTION
**Pull request by munikes**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [ ] includes a link to user documentation.

### CODE REVIEW

**Comment by MuckT** [comment]
@munikes when I navigate to https://ethix.ethichub.com I see that Celo is disabled. Is it possible to enable this for testing?

**Comment by MuckT** [comment]
@munikes the staking layout on mobile is a bit narrow compared to the other sections, but otherwise looking good!

**Comment by jordiethichub** [comment]
> @munikes the staking layout on mobile is a bit narrow compared to the other sections, but otherwise looking good! 

@MuckT : 1. please be advice that we deployed new version with little updates: a) right now , bonds window is open by default when user access dapp b) We included link to pool and farming opportunity  CELO ETHIX in Symmetric for easy access c) We changed logo ETH for Logo CELO in General staking. 2. Please can you give more detailed feedback about narrow tabs? Do you consider that grey tabs must be wider with this new version? 3. We will provide user documentation link updated as soon as possible.

**Comment by jordiethichub** [comment]
> > To make a submission to the Dapps Page, please complete the task lists
> > below; otherwise remove them.
> 
> Your Dapp:
> 
> * [x]  connects to Valora via WalletConnect V1 or DAppKit;
> * [x]  must be mobile-first or mobile responsive;
> * [x]  is in one of the existing categories; and
> * [ ]  includes a link to user documentation.

Pls see attached general documentation and tutorial link https://docs-ethix.ethichub.com/v/english/

**Comment by eun-plata** [comment]
> > To make a submission to the Dapps Page, please complete the task lists
> > below; otherwise remove them.
> 
> Your Dapp:
> 
> * [x]  connects to Valora via WalletConnect V1 or DAppKit;
> * [x]  must be mobile-first or mobile responsive;
> * [x]  is in one of the existing categories; and
> * [x]  includes a link to user documentation.

@MuckT please, find the tutorials at https://docs-ethix.ethichub.com/v/english/tutorials/ethix-on-celo
Thank you!!

**Review by MuckT — APPROVED** [review]
@eun-plata thanks for adding links to the docs LGTM!

**Review by MuckT — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
