### PR TITLE
Submit heymate for the bakeoff

### PR DESCRIPTION
**Pull request by heymateag**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [ ] is in one of the existing categories; and
- [x] includes a link to user documentation.

Please confirm you have:

- [x] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [x] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by aleksey-nov** [comment]
Hi @heymateag,
Thanks for submitting heymate for the Bakeoff!

In order to get approved, the dapp should:
- Connect to Valora. I wasn't able to do so - when I tap on connect wallet after signing in with my Telegram account, I see the QR-code which I can't scan since I am already on my phone.
- Provide user docs on how to use the dapp. I think this is especially needed in case with your dapp - being signed in to my Telegram account was completely unexpected for us and we believe will be the same for our users.

It will be great if you can fix these issues and let us know before Feb 28. So we can review again and add to the Bakeoff.

Thanks in advance!

**Review by alimusavi67 — APPROVED** [review]

**Review by Ankitkumarrana — APPROVED** [review]

**Comment by jeanregisser** [comment]
Gentle reminder, you need to address the feedback we left above by Feb 28th.
Let me know if you have any question.

**Comment by Ankitkumarrana** [comment]
> Hi @heymateag, Thanks for submitting heymate for the Bakeoff!
> 
> In order to get approved, the dapp should:
> 
> * Connect to Valora. I wasn't able to do so - when I tap on connect wallet after signing in with my Telegram account, I see the QR-code which I can't scan since I am already on my phone.
> * Provide user docs on how to use the dapp. I think this is especially needed in case with your dapp - being signed in to my Telegram account was completely unexpected for us and we believe will be the same for our users.
> 
> It will be great if you can fix these issues and let us know before Feb 28. So we can review again and add to the Bakeoff.
> 
> Thanks in advance!

@aleksey-nov Sorry for the delay in reply 

1. If you use the mobile version of our web app, it will now prompt you to sign transactions using either Valora or Heymate app. Since our app is a hybrid DApp (uses mobile nr to sign into Telegram) and Wallet Apps (e.g. Valora) to sign transactions on Celo.
2. Please find attached the link to our user onboarding document created for the Valora Bakeoff: [Heymate User onboarding document](https://docs.google.com/document/d/e/2PACX-1vQnjQWbPfCXfwpQkomUy2PiD_FTlCvSS6ZMO9mHXgHEfnwKnOa5SyYnqOq7XwG_zsHP1g7k_vqg7Tan/pub)

**Comment by Ankitkumarrana** [comment]
> Gentle reminder, you need to address the feedback we left above by Feb 28th.
> Let me know if you have any question.

@jeanregisser Sorry for the delay. Just responded to the comment above and provided the Heymate user documentation link.

**Review by Ankitkumarrana — APPROVED** [review]
All good.

**Review by alimusavi67 — APPROVED** [review]
its ok

**Comment by jeanregisser** [comment]
Great, I'll take a look soon!

**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Review by Ankitkumarrana — APPROVED** [review]
It's good

**Comment by dominiquejane** [comment]
@Ankitkumarrana 

On your web app the text for Social Commerce and DEFI Services are using the same text as the Heymate Telegram section.

The user docs should be accessible before a user has to sign in or register (I don't think many users would be willing to use an app they know nothing about).

**Comment by jeanregisser** [comment]
I was able to sign-in however when going to the Wallet section, pressing "Open Wallet App" prompted me to open "Rainbow" instead of Valora.
This was on iOS.

This is because I have both Rainbow and Valora installed on the phone I used for testing.
On Android the system prompts me to select which app I want to open for the `wc:XXX` link.
However iOS doesn't do this. You should use the [WalletConnect QR modal](https://docs.walletconnect.com/mobile-linking) which prompts the user to select the wallet they have.

image

**Comment by jeanregisser** [comment]
Any update @heymateag?

**Comment by Ankitkumarrana** [comment]
> @Ankitkumarrana
> 
> On your web app the text for Social Commerce and DEFI Services are using the same text as the Heymate Telegram section.
@dominiquejane The promotional text on the splash screens have been fixed.
> 
> The user docs should be accessible before a user has to sign in or register (I don't think many users would be willing to use an app they know nothing about).
@dominiquejane There is now a help link under the Start button that takes the user to our docs (prior to signing in to the app). Once the app is open, there is also a help menu item that points to the same document.

**Comment by Ankitkumarrana** [comment]
> I was able to sign-in however when going to the Wallet section, pressing "Open Wallet App" prompted me to open "Rainbow" instead of Valora. This was on iOS.
> 
> This is because I have both Rainbow and Valora installed on the phone I used for testing. On Android the system prompts me to select which app I want to open for the `wc:XXX` link. However iOS doesn't do this. You should use the [WalletConnect QR modal](https://docs.walletconnect.com/mobile-linking) which prompts the user to select the wallet they have.
> 
> image

@jeanregisser Thanks for pointing this out! We are using WC Modal now in our latest release.

**Comment by Ankitkumarrana** [comment]
> Any update @heymateag?

@jeanregisser just did the updates, see comments above thanks.
FYI: we are moving to self-hosted WC relay server, this should happen hopefully today otherwise ASAP.

**Comment by jeanregisser** [comment]
Thanks I just retried but it directly opens the QR code instead of letting me choose Valora.
So right now I'm unable to connect it to Valora.

**Comment by Ankitkumarrana** [comment]
> Thanks I just retried but it directly opens the QR code instead of letting me choose Valora. So right now I'm unable to connect it to Valora (mobile to mobile flow, which is what most Valora users will do).
> 
> 

@jeanregisser We noticed from your screenshot that you were referencing the cloudfront URL, we have changed the reference in valora-dapp-list.json to point to https://web.heymate.works/ instead. We also resolved the conflicts in base.json. Please ensure you are using the new URL, we were able to sign with Valora so would need more details to troubleshoot, thanks for your patience and support!

**Comment by jeanregisser** [comment]
I just tried https://web.heymate.works and still see the same issue, I can't connect it in the mobile to mobile use case because it's showing the QR code instead of opening the deep link to Valora:

**Comment by jeanregisser** [comment]
Hey, I see you were very close to making it 😯

Addressing our feedback by March 3rd @ 11:59 pm PST (UTC -8:00) was necessary to be part of the Bake Off.
Though you now don't qualify anymore as a Bake Off participant, I'm looking forward to including heymate in the Valora's Dapps page as soon as the feedback is addressed.

Ping me when you want me to have a look again.

Thanks so much! 🙌 🙏

**Comment by silasbw** [comment]
Closing this, but feel free to address feedback or reach out with more questions if you're still interested in getting listed.

**Pull request closed without merging**
