### PR TITLE
Add Ariswap to Dapp List

### PR DESCRIPTION
**Pull request by maxwellchua**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

Please confirm you have:

- [x] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [x] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by jeanregisser** [comment]
@maxwellchua Gentle reminder, you need to have WalletConnect support + user facing docs by Feb 28th if you wanna participate in the Bake Off.
Let me know if you have any question.

**Comment by maxwellchua** [comment]
@jeanregisser thanks for the reminder. Just a quick question, what is the expected content of the user documentation. Is this a documentation of the site, with its features and how it interacts with the blockchain? Or is it more of a documentation for the concepts of blockchain and NFTs?

**Comment by jeanregisser** [comment]
Hey please see our [recommendations for user documentation](https://github.com/valora-inc/dapp-list/blob/main/user-documentation-best-practices.md).

**Comment by AriSwap** [comment]
Hello. I am not able to click on the check box tfor the user docs.

**Comment by AriSwap** [comment]
We have all docs available in ariswap.net under section ARI Learn.  Including how to create a Valora wallet

**Comment by jeanregisser** [comment]
@maxwellchua @AriSwap I'm unable to use WalletConnect with Ariswap.
I only see the MetaMask option on https://ariswap.co/login



Are you going to support WalletConnect?

**Comment by AriSwap** [comment]
Yes.
Max is going to complete this, this week.

Alex

**Comment by jeanregisser** [comment]
@AriSwap, just to be extra sure you know this, the deadline for addressing all feedback is today Feb 28th by end of day.

**Comment by AriSwap** [comment]
Oh.
Unfortunately we will not be able to have this completed today.  Max is our
Dev and he was out this weekend and today.  He will be back tomorrow.

**Comment by jeanregisser** [comment]
**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Comment by jeanregisser** [comment]
Any update @AriSwap?

**Comment by AriSwap** [comment]
Will have the update in about an hour.  Will be speaking with dev team and
Max on our weekly sprint review call.  It is at 8am EST. So right after
that I will let you know

Alex

**Comment by AriSwap** [comment]
Hello Jean,

Spoke with Max and the team.  Go ahead and proceed without us.  We are
integrating Valora and already have in our test environment.  However
instead of simply launching "sign in" with Valora we want to integrate
Valora through the entire environment and flow.  So integrating Valora into
the sell NFT functionality, buy now, and auction place bid,  This is all
being tested since it deals with users money.  Max feels
comfortable bringing live in a few days.  Valora is such an amazing product
and we want to ensure we have it set to feature it properly

Thank you


*CEO-Founder*
*Ari Swap Corp*
*(727)834-0994*
*Ariswap.net*

**Comment by jeanregisser** [comment]
Thanks for the update and looking forward to see this.

**Comment by jeanregisser** [comment]
Hey, we see you were very close to making it 😯

Addressing our feedback by March 3rd @ 11:59 pm PST (UTC -8:00) was necessary to be part of the Bake Off contest.
Though you now don't qualify anymore as a Bake Off participant, we're looking forward to including Ariswap in the Valora's Dapps page as soon as the feedback is addressed.

Ping us when you want us to have a look again.

Thanks so much! 🙌 🙏

**Comment by silasbw** [comment]
Closing this, but feel free to address feedback or reach out with more questions if you're still interested in getting listed.

**Comment by dominiquejane** [comment]
Re: support content

The ["how it works"](https://ariswap.co/how-it-works) section is a bunch of lorem ipsum. I do see a "how it works" section on the main page so maybe should just get rid of the page I linked or put the content from the main page into that link.

The Help Center page is also empty.

However, I do see the comment about support content on ariswap.net. If this is where the support content is intended to live then I recommend removing the pages mentioned above and adding a link on ariswap.co to redirect to the $ARI Learn page.

**Comment by AriSwap** [comment]
Hello Thank you

The How It Works on the Home Page which is between the Live Auction and Top
Seller section of Ariswap.co is active and directs users how to log in.

The How it works in the footer we will redict to the .net site section of
the learn Valora

**Comment by AriSwap** [comment]
Hello all trying to hit the check mark for Connects to Valora but it won't let me

**Comment by silasbw** [comment]
Hey @AriSwap, do you mind resolving the reported conflicts?

**Review by jeanregisser — APPROVED** [review]

**Pull request merged**
