### PR TITLE
Add talent protocol to dapp list

### PR DESCRIPTION
**Pull request by francisco-leal**
Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

Please confirm you have:

- [x] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [x] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by dominiquejane** [comment]
@francisco-leal 
I'm checking user docs and so I tried to sign up but the Terms and Conditions checkbox was unclickable.
1. Can you fix this?
2. Are there links to user docs that don't require a login to the website?

**Comment by francisco-leal** [comment]
Hey @dominiquejane! Thanks for reporting that bug, we released some major changes yesterday and it did include that bug that has since been solved.

We have a guide on our public Notion page and it is also available from the menu inside the dapp: https://talentprotocol.notion.site/User-Guide-ab42205b0294491e98364dec24d5ad5e

**Comment by dominiquejane** [comment]
@francisco-leal 
Ah, I see what happened now. I was using a referral link but it doesn't have a way to lead users back to your main page:
https://beta.talentprotocol.com/sign_up?code=SUP-VALORA

Your docs are great, but I'm concerned that if we use this link it will be a blocker for users who want to know more about Talent Protocol before registering. My suggestion:
- provide a link to the user docs on your referral/login pages, or
- provide a backlink to the main website on your referral pages

**Comment by francisco-leal** [comment]
That's a great idea, thank! I'll look into adding that

**Comment by jeanregisser** [comment]
@francisco-leal  Gentle reminder, you need to have WalletConnect support + user facing docs by Feb 28th if you wanna participate in the Bake Off.
Let me know if you have any question.

**Comment by jeanregisser** [comment]
**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Comment by francisco-leal** [comment]
hey @jeanregisser and @dominiquejane! I've just made a release to our Beta that adds support for valora & adds the requested references to the user guide. Since the deadline has been postponed let me know if you have any more feedback so that we can address it.

From my side I have a question, feel free to redirect me to a better place to ask it but is there any way to track ERC20 token balances in the valora app? Since we're talking about social tokens it's hard to meet the requirements

**Comment by jeanregisser** [comment]
> From my side I have a question, feel free to redirect me to a better place to ask it but is there any way to track ERC20 token balances in the valora app? Since we're talking about social tokens it's hard to meet the requirements

Can you ask in our [#dapp-dev](https://discord.com/channels/886972503560433675/887422238071087154) channel on discord?

**Comment by gsalaiz-Valora** [comment]
Hi @francisco-leal! This is Gus, from Valora, the bottom to connect the wallet to your dapp is not working, could you take a look?

**Pull request merged**
