### PR TITLE
add cyberbox items for valora bakeoff

### PR DESCRIPTION
**Pull request by richardyu65**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [X] connects to Valora via WalletConnect V1 or DAppKit;
- [X] must be mobile-first or mobile responsive;
- [X] is in one of the existing categories; and
- [X] includes a link to user documentation.

Please confirm you have:

- [X] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [X] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by jeanregisser** [comment]
Thanks for your submission! 🙌 

It's almost good! I noticed a few problems though.
1. I tried buying [a NFT which is listed for sale](https://cyberbox.art/collections/nfet/3370) but couldn't. The experience was a bit confusing, it didn't guide me very well for approving and then signing the transaction. The button stayed as "Pending Confirmation...` the whole time. And then sign failed `execution reverted: Token is not for sale`


2. the WalletConnect session doesn't specify an `icons` array resulting in a suboptimal experience for Valora users. Valora tries to use `https://cyberbox.art/favicon.ico` if the `icons` field is not set or empty but currently there's it's a 404.
 
Could you please address these? 🙏

**Comment by richardyu65** [comment]
> Could you please address these? 🙏

**Comment by richardyu65** [comment]
> 

Thanks for your feedbacks with detail!

I will address them ASAP.

**Comment by jeanregisser** [comment]
Great, I'll take a look soon!

**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Comment by richardyu65** [comment]
@jeanregisser I got it. Thanks for your all of detail look and good feedbacks.

I will address them before 3rd of March.

**Comment by jeanregisser** [comment]
Any updated @richardyu65?

**Comment by olagrinchen** [comment]
Hi @jeanregisser I showed title with logo of Wallet Connection.
Also I fixed auto open issue mostly and check it myself for now, but it needs 1 or 2 days more to complete.
Could you give me more time to address feedbacks for auto open and signing transaction completely?
Sorry for delay.

**Comment by richardyu65** [comment]
Hi @jeanregisser I showed title with logo of Wallet Connection.
Also I fixed auto open issue mostly and check it myself for now, but it needs 1 or 2 days more to complete.
Could you give me more time to address feedbacks for auto open and signing transaction completely?
Sorry for delay.

**Comment by jeanregisser** [comment]
Hey, I see you were very close to making it 😯

Having a fully working integration with Valora was necessary to be part of the Bake Off.
Though you now don't qualify anymore as a Bake Off participant, I'm looking forward to include Cyberbox in the Valora's Dapps page as soon as the remaining issues are fixed.

Ping me when you want me to have a look again. 🙏

**Comment by olagrinchen** [comment]
@jeanregisser We have completed new version of our DApp. 

Could you look at it?

Let me know if you have some feedback for our DApp.

We want that add our DApp to Valora if all looks good

**Comment by richardyu65** [comment]
Hi @jeanregisser  We have completed new version of our DApp.

Could you look at it? (https://cyberbox.art)

Let me know if you have some feedback for our DApp.

We want that add our DApp to Valora if all looks good

**Comment by jeanregisser** [comment]
Hey @richardyu65, sorry for the delay.
I just took a look and had some issues loading the NFTs in different collections. It's staying with the loading spinner.

Example on https://cyberbox.art/collections/cak:



Probably a temporary server/network issue. I'll retry tomorrow.

**Comment by richardyu65** [comment]
@jeanregisser Thanks for your checking.
NFTs loading works as well in collection which you took a look and I can't reproduce issue.
Could you check again tomorrow?

**Comment by richardyu65** [comment]
@jeanregisser Thanks for feedback!
Let me check and fix it.
I have some questions:
- Did you connect your Rainbow wallet to Cyberbox before buy NFT?
- What should we support in this case?

**Comment by richardyu65** [comment]
Hi @jeanregisser I reproduced issue from my side which you found. Finally I fixed it and we deployed it to Cyberbox.
Could you check again?

**Comment by jeanregisser** [comment]
All good! Thanks so much 🎉

**Comment by richardyu65** [comment]
@jeanregisser  Sorry for very late response. Thanks a lot for your help and checking!

**Pull request merged**
