### PR TITLE
Add ReSource dapp

### PR DESCRIPTION
**Pull request by Bridgerz**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [ ] connects to Valora via WalletConnect V1 or DAppKit;
- [ ] must be mobile-first or mobile responsive;
- [ ] is in one of the existing categories; and
- [ ] includes a link to user documentation.

### CODE REVIEW

**Comment by jeanregisser** [comment]
Thanks for submitting ReSource!

Could you add a logo?
> The logo of the Dapp must be a 256 x 256 PNG added to the [assets](https://github.com/valora-inc/dapp-list/tree/main/assets) folder.

**Comment by Bridgerz** [comment]
@jeanregisser apologies! logo added

**Comment by jeanregisser** [comment]
Thanks, here some more feedback:
- Tried a small stake and it just said “Approving” - never prompted me to check Valora again. Could you improve this? I might have waited forever as a newbie.
- I can’t see any proof anywhere that I staked. Including on the website. It’s like I didn’t take that action. Is there a place that I missed?
- One optional comment about the dapp description: I don't know if I'm the only one, but "Member-owned bankless platform for self-reliant communities" doesn't really mean a lot to me. it would help if the description were a bit more concrete and helped users understand why they should visit, rather than describing the product vision.

**Comment by Bridgerz** [comment]
- Will add a "Check Valora App" pop up to make it more clear.
- You have to refresh the dapp to see deposits in the rewards tab... this bug is being fixed now.
- Description will be updated accordingly. 

Will update PR as soon as these are addressed. Thanks for the input!

**Comment by Bridgerz** [comment]
@jeanregisser 
We've added a "Confirm transaction on connected wallet app" toast for Valora and Wallet connect. 
FYI we're using the celo-react library and `const { walletType } = useCelo()
` returns "WalletConnect" even if the connected wallet is Valora

We've also fixed the state issue when staking. Once users stake, they'll be able to see their total amount deposited updates in the "Rewards" tab on the staking modal.

You'll also find I've updated the description. 

Thanks again for the input.

**Comment by Bridgerz** [comment]
@jeanregisser have you had a chance to take a look at this?

**Comment by jeanregisser** [comment]
Thanks @Bridgerz ! I took a look again and here are the problems I faced:
- I swapped some cUSD on Ubeswap to get ~0.14 SOURCE tokens.
Screenshot 2022-06-22 at 15 33 23

- After connecting to ReSource, it says I have 0 SOURCE tokens. I cleaned my cache and it says the same:


- On a minor note, tapping "View on Explorer" opens "https://explorer.celo.orgaddress/0x1148..." instead of ""https://explorer.celo.org/address/0x1148..."

- Maybe related to my 0 SOURCE balance, but it seems it's not possible to enter a decimal when the OS keyboard is set to a region using `,` instead of `.` as a decimal separator:

image

Could you help me understand these? 🙏

**Comment by jeanregisser** [comment]
Great thanks and I now see my 0.14 SOURCE 👍 

Last problem is with the PR, Test is not running because it was forked to an org repo that doesn't allow that.
I'll manually merge it first thing tomorrow.

**Comment by Bridgerz** [comment]
@jeanregisser Thanks a bunch!

**Comment by jeanregisser** [comment]
Manually merged in 706417a0de8886f99b566024247cf47be35d1c70

**Pull request closed without merging**
