### PR TITLE
Award Pool bakeoff application

### PR DESCRIPTION
**Pull request by ruvnet**
Including Award Pool in the Bake-off!

> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [ ] connects to Valora via WalletConnect V1 or DAppKit;
- [ ] must be mobile-first or mobile responsive;
- [ ] is in one of the existing categories; and
- [ ] includes a link to user documentation.

Please confirm you have:

- [ ] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [ ] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by jeanregisser** [comment]
Hey @ruvnet! Thanks for your submission! 🙌 
Some parts are however missing.
You also need the icon in the [asset](https://github.com/valora-inc/dapp-list/tree/main/assets) folder and the dapp info in [src/valora-dapp-list.json](https://github.com/valora-inc/dapp-list/blob/main/src/valora-dapp-list.json)

You can have a look at this tutorial which details all of this: https://www.youtube.com/watch?v=t6qX85P02IQ

**Comment by jeanregisser** [comment]
Hey @ruvnet, your submission is received but not yet approved.
Please see my message above.

Also one important point is that your dapp connects to Valora via WalletConnect v1 or Dappkit.
I don't yet see this. Do you have any plan to support this?

You have until Feb 28th to address our feedback.

**Comment by ruvnet** [comment]
It's mobile embed, so it should be fairly self-evident. Similar to how Valora itself doesn't include any user documentation. We have roughly 200,000 users currently.

**Comment by ruvnet** [comment]
This might be helpful https://awardpool.com/contact

**Comment by lisaw-valora** [comment]
Hi ruvnet - Valora has user facing documentation at support.valoraapp.com, which can be found in Valora in the menu > Help > Frequently Asked Questions

I'm having a look at the provided link on mobile and can't find user-facing docs there either.  Can you provide the path to the documentation?  

https://awardpool.com/contact is great! I can't find this page from the links  provided for the bakeoff.

**Comment by jeanregisser** [comment]
Hey @ruvnet as stated [in my previous message](https://github.com/valora-inc/dapp-list/pull/79#issuecomment-1036466889) this PR can't yet be accepted:
> Some parts are however missing.
You also need the icon in the [asset](https://github.com/valora-inc/dapp-list/tree/main/assets) folder and the dapp info in [src/valora-dapp-list.json](https://github.com/valora-inc/dapp-list/blob/main/src/valora-dapp-list.json)
>
> You can have a look at this tutorial which details all of this: https://www.youtube.com/watch?v=t6qX85P02IQ

**Comment by ruvnet** [comment]
our wallet connect login/signup is live.

**Comment by jeanregisser** [comment]
Gentle reminder, you need to address the feedback we left above by Feb 28th.
Let me know if you have any question.

**Comment by ruvnet** [comment]
i completed the required steps.

**Comment by jeanregisser** [comment]
Closing this one, since you opened https://github.com/valora-inc/dapp-list/pull/112

**Pull request closed without merging**
