### PR TITLE
add goodghosting submission to valora bakeoff

### PR DESCRIPTION
**Pull request by fodisi**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [X] connects to Valora via WalletConnect V1 or DAppKit; (in QA w/ GoodGhosting team)
- [X] must be mobile-first or mobile responsive;
- [X] is in one of the existing categories; and
- [X] includes a link to user documentation.

Please confirm you have:

- [X] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [X] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by aleksey-nov** [comment]
Hi @fodisi,
Thanks for submitting your dapp to participate in the Bakeoff!

One of (and the most important) conditions to participate, is that dapp must connect to Valora. Unfortunately, it seems like your dapp supports only Metamask and Ledger at this time.

Please add support for Valora (using WalletConnect v1) and let us know so we can review your submission again.

Thanks!

**Comment by fodisi** [comment]
> Hi @fodisi, Thanks for submitting your dapp to participate in the Bakeoff!
> 
> One of (and the most important) conditions to participate, is that dapp must connect to Valora. Unfortunately, it seems like your dapp supports only Metamask and Ledger at this time.
> 
> Please add support for Valora (using WalletConnect v1) and let us know so we can review your submission again.
> 
> Thanks!

hey @aleksey-nov 
Thanks a lot for your quick reply. We're indeed trying to add support for valora - we didn't deployed it to prod yet because of the issues we're facing. Chatting in the Valora discord channel to try to get it fixed. 

Just to understand the clear requirements:
We're able to use Valora to sign transactions on a cellphone if the user is using the website on a desktop browser (our staging site).

However, facing issues to get it to work properly on iOS devices.
What are the exact requirements in terms of devices/platforms for the bakeoff program?

Thanks a lot.

**Comment by fodisi** [comment]
> > Hi @fodisi, Thanks for submitting your dapp to participate in the Bakeoff!
> > One of (and the most important) conditions to participate, is that dapp must connect to Valora. Unfortunately, it seems like your dapp supports only Metamask and Ledger at this time.
> > Please add support for Valora (using WalletConnect v1) and let us know so we can review your submission again.
> > Thanks!
> 
> hey @aleksey-nov Thanks a lot for your quick reply. We're indeed trying to add support for valora - we didn't deployed it to prod yet because of the issues we're facing. Chatting in the Valora discord channel to try to get it fixed.
> 
> Just to understand the clear requirements: We're able to use Valora to sign transactions on a cellphone if the user is using the website on a desktop browser (our staging site).
> 
> However, facing issues to get it to work properly on iOS devices. What are the exact requirements in terms of devices/platforms for the bakeoff program?
> 
> Thanks a lot.

Hi folks,
Just aligning - we'll deploy support for Valora in our production website on Monday, Feb/28, early EST time.
I'll update you here once it's live.
Thanks

**Comment by fodisi** [comment]
@jeanregisser @aleksey-nov 
We just deployed support for Valora app on our production website https://goodghosting.com.

Please let us know if there's anything else needed for the bakeoff or if we're in 🙏 

Thank you.

**Comment by jeanregisser** [comment]
Great, I'll take a look soon!

**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Comment by jeanregisser** [comment]
Nice, I was able to successfully connect with Valora using WalletConnect.

I however couldn't find an open Celo pool to test transactions. Is there one that will open soon?
Or is there another way I could test further?

**Comment by fodisi** [comment]
hi @jeanregisser 
Yeah, unfortunately, at the moment, goodghosting pools are "time-boxed" - users have a period to join.
What we can do is to create a testing pool and deploy it on a separate URL that is not goodghosting.com.
We'd have to do so, otherwise all users would be able to join, and that's not gonna be a real pool.
Let us set that up for you and we'll update it back here shortly.

PS: the codebase is still the same as production https://goodghosting.com. Just the testing url will be different, so the pool isn't available on production.

**Comment by camolezi** [comment]
@jeanregisser @fodisi 
 
I've deployed a demo game on Celo on a separate URL 
https://deploy-preview-286--reverent-kilby-275fae.netlify.app/#/

You can find it on the "pools" page, it's called "Celo Bakeoff Demo Pool". Feel free to reach out if you encounter any issues.  
Cheers!

**Comment by jeanregisser** [comment]
Great! it worked! 🎉 

Do you plan on having an open Celo pool during March?

**Comment by fodisi** [comment]
> Great! it worked! 🎉
> 
> Do you plan on having an open Celo pool during March?

Hi @jeanregisser . Glad it worked.
Yes, we're launching a Celo pool next week to celebrate Women's Day!

**Review by jeanregisser — APPROVED** [review]

**Pull request merged**
