### PR TITLE
Add Mezumo to Valora

### PR DESCRIPTION
**Pull request by gnardini**
Mezumo:

- [✔️] connects to Valora via WalletConnect V1 or DAppKit;
- [✔️] must be mobile-first or mobile responsive;
- [✔️] is in one of the existing categories; and
- [✔️] includes a link to user documentation: http://docs.mezumo.xyz/

### CODE REVIEW

**Comment by MuckT** [comment]
@gnardini is the .png included perhaps a .jpg that was renamed? Running `file -I mezumo.png` is returning the following.
Screen Shot 2022-07-21 at 6 11 20 PM

**Comment by gnardini** [comment]
That's weird, it was indeed jpg in the beginning but I used a converter to turn it into png. I've asked the designer for a png version, should have it ready by tomorrow.

**Comment by gnardini** [comment]
@MuckT updated the logo!

**Comment by MuckT** [comment]
@gnardini Thanks LGTM!

**Review by MuckT — APPROVED** [review]
🚀

**Pull request merged**
