### PR TITLE
 Add Blockcash to Dapp

### PR DESCRIPTION
**Pull request by kandragu**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [ ] connects to Valora via WalletConnect V1 or DAppKit;
- [ ] must be mobile-first or mobile responsive;
- [ ] is in one of the existing categories; and
- [ ] includes a link to user documentation.

Please confirm you have:

- [ ] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [ ] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by aleksey-nov** [comment]
Hello @kandragu,

Thanks for submitting your dapp for the bakeoff. We were not able to review the iOS version. TestFlight doesn't seem to be working. Can you please fix it? Or perhaps it is possible to submit the app to the App Store? This will be even better (you still have. a week to do so).

**Comment by kandragu** [comment]
App is released only on Google Play, 
It will not be released on Appstore due to the Apple guideline.

**Comment by jeanregisser** [comment]
@kandragu ok but can you please fix the TestFlight from your website? It doesn't currently work.

image

**Comment by jeanregisser** [comment]
@kandragu Gentle reminder, the deadline for addressing all feedback is today Feb 28th by end of day if you wanna participate in the Bake Off.
Let me know if you have any question.

**Comment by jeanregisser** [comment]
**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Comment by jeanregisser** [comment]
Any update @kandragu?

**Comment by jeanregisser** [comment]
Hey, I see you were very close to making it 😯

Addressing our feedback by March 3rd @ 11:59 pm PST (UTC -8:00) was necessary to be part of the Bake Off.
Though you now don't qualify anymore as a Bake Off participant, I'm looking forward to including Blockcash in the Valora's Dapps page as soon as the feedback is addressed.

Ping me when you want me to have a look again.

Thanks so much! 🙌 🙏

**Comment by kandragu** [comment]
hi @jeanregisser  
Thanks so mush, I have removed the appstore link and Testflight . it should be fine now.

**Pull request closed without merging**
