### PR TITLE
Add Trelis Pay to Dapp List

### PR DESCRIPTION
**Pull request by manashmandal**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

Please confirm you have:

- [x] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [x] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by dominiquejane** [comment]
Small typos: 

https://docs.trelis.com/
"Trelis Pay is non-custodial and Trelis does not have **accepts** to merchant funds."

https://docs.trelis.com/pricing-and-fees
"**Treils** fees are in addition to fees charged by the payment network."

https://docs.trelis.com/extras/support-and-contact
https://docs.trelis.com/pricing-and-fees
"hello@**[this domain]**"

**Comment by manashmandal** [comment]
Hi @dominiquejane, sorry for the typos. Will fix and let you know. Thank you.

**Comment by manashmandal** [comment]
Hi @dominiquejane the typos are fixed. Just a note, `"hello@[this domain]"` is intended because of spamming. Thanks.

**Comment by jeanregisser** [comment]
Thanks! Could you check the "Allow edits by maintainers" box toward the bottom right side of the PR?
This is needed for the test check to run and this way we can also merge/resolve conflicts for you. 🙏 
Screenshot 2022-02-16 at 09 33 33

**Comment by manashmandal** [comment]
@jeanregisser Hi Jean, can't seem to find the option :(

**Comment by jeanregisser** [comment]
Ah, It's possible you have to create a new PR and check that box when creating it.
Could you try?

**Comment by manashmandal** [comment]
> Ah, It's possible you have to create a new PR and check that box when creating it. Could you try?

Yes I can do that, let me create a new PR.

**Comment by jeanregisser** [comment]
Any issue creating the new PR @manashmandal?

**Comment by dominiquejane** [comment]
@manashmandal When you say "spamming" do you mean you are trying to prevent bots from picking up your email?
If so, could you add additional information for users who may not fully understand how to interpret these instructions?
Example: "please replace `[this domain]` with `trelis.com`"

**Comment by manashmandal** [comment]
> @manashmandal When you say "spamming" do you mean you are trying to prevent bots from picking up your email? If so, could you add additional information for users who may not fully understand how to interpret these instructions? Example: "please replace `[this domain]` with `trelis.com`"

Yes exactly what you meant. Thanks for pointing that out. Updating the instructions.

**Comment by manashmandal** [comment]
> Any issue creating the new PR @manashmandal?

While creating the new PR didn't see the option.

**Pull request closed without merging**
