### PR TITLE
Plastiks

### PR DESCRIPTION
**Pull request by garciapd**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by silasbw** [comment]
Thanks for the submission @garciapd :raised_hands:   We'll take a look in the next few days!

**Comment by lisaw-valora** [comment]
Thanks for submitting and sharing on Discord.  Beautiful user-facing docs, but did not see a connection about how to connect using Valora. Would love to see such a section added.

**Comment by garciapd** [comment]
Thanks! you mean in our Gitbook?

https://plastiks.gitbook.io/plastiks-docs/rFkbTd5kDEGr1avfk2Bc/marketplace/faq

**Comment by lisaw-valora** [comment]
Yes, exactly.

**Comment by garciapd** [comment]
@lisaw-valora we have added this

https://plastiks.gitbook.io/plastiks-docs/rFkbTd5kDEGr1avfk2Bc/marketplace/guides/getting-started/connect-to-marketplace-using-valora-app

**Comment by lisaw-valora** [comment]
The new docs look good. Thank you for adding them!

**Comment by jeanregisser** [comment]
Thanks! Could you also make sure your icon is displayed when connecting in Valora?

Right now it doesn't show anything.



There is an option to set an image for the WalletConnect request. Valora supports `png`, `jpg` and `ico`.

Alternatively, if the image is not set Valora uses `${your_url}/favicon.ico`. 
But right now it's empty: https://app.plastiks.io/favicon.ico

**Comment by garciapd** [comment]
@jeanregisser fixed!

**Comment by jeanregisser** [comment]
Amazing! 👍

**Review by jeanregisser — APPROVED** [review]

**Pull request merged**
