### PR TITLE
Submit Flywallet for bakeoff 👏🏾

### PR DESCRIPTION
**Pull request by uchebuego**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

Please confirm you have:

- [x] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [x] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by lisaw-valora** [comment]
Some quick comments on the user-facing docs. They're enough for the bakeoff; however, we encourage you to add a short paragraph about what Flywheel is and how it helps.  These should be aimed at a newcomer to defi. We'd recommend that paragraph on this [Notion page](https://chain-cover-7ae.notion.site/Learn-more-about-flywallet-Pro-Web3-Crypto-623560f2c56643698978b5469d77de4b) - which is where "About" lands when starting [here](https://pro.flywallet.io/)

**Comment by uchebuego** [comment]
Hello @lisaw-valora. That notion page is intended to serve as user documentation. It has as well been updated with more information that may help the user while exploring the product. Any thoughts on that?

**Comment by lisaw-valora** [comment]
Hi @uchebuego ! I went to review again and the About page isn't loading.  Even when I go directly here: https://pro.flywallet.io/about it goes back to pro.flywallet.io.  I can not see the updates you've made.

**Comment by uchebuego** [comment]
Sorry about that @lisaw-valora ... We've sent an update to fix that. The "ABOUT" button now links to the documentation on notion.

**Review by jeanregisser — APPROVED** [review]

**Pull request merged**
