### PR TITLE
feat: add toucan to the dapp list

### PR DESCRIPTION
**Pull request by MuckT**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by MuckT** [comment]
@Niwilai does the url used look good to you?

**Comment by Niwilai** [comment]
@MuckT yes URL looks good. Thanks for your feedback, noted.

**Comment by Niwilai** [comment]
@MuckT I am now having some availability to pick this up again. Sorry for the delay!

> When connection via mobile browser I am able to interact with Toucan; however, when I attempt to use Wallet connect on a desktop client I am seeing 401's from https://mainnet.infura.io/v3/undefined

Just to confirm, you are trying to connect on a desktop device via scanning the QR on your mobile app, correct?

**Comment by MuckT** [comment]
@Niwilai I am able to connect via QR code and on a mobile browser and the balance is now displaying in CELO. 
It's a bit unclear how I can acquire BCT or NCT on CELO, but I do see connection steps in the [user documentation](https://docs.toucan.earth/toucan/cross-chain/user-guide).

**Review by jeanregisser — APPROVED** [review]

**Pull request merged**
