### PR TITLE
Add pixpress

### PR DESCRIPTION
**Pull request by devarellin**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by devarellin** [comment]
Hey @MuckT. Sorry, I accidentally closed the previous PR. Opened a fixed and synced new one here.

**Comment by MuckT** [comment]
@devarellin it looks like when connecting both Valora and Wallet Connect take me to Wallet Connect Prompt. https://github.com/celo-org/react-celo might be a good example to take a look at.

**Comment by devarellin** [comment]
Hey, @MuckT it's meant to at this moment because Valora is listed inside the wallet connect prompt as well.
The symmetric app which is listed on Valora's app list also does the trick.

In the future, we'll improve it. 

btw, we use `react-celo` when we first submit this PR but now we removed it because it has the bug that no prompt is up when doing transactions.

**Review by MuckT — APPROVED** [review]
🚀

**Pull request merged**
