### PR TITLE
add cask

### PR DESCRIPTION
**Pull request by masha256**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by MuckT** [comment]
@masha256 - only change I am seeing is having the image as 256px by 256px instead of 250px by 250 px.

**Comment by masha256** [comment]
@MuckT image fixed

**Comment by MuckT** [comment]
@masha256 it looks like there are some mobile layout issues wallet and my flows pages.

https://user-images.githubusercontent.com/26950305/193698445-9a9d2b5b-7f4f-4acc-841b-5fa392cf311d.mov

**Comment by masha256** [comment]
@MuckT Our UI team has cleaned things up. Hopefully its good enough to be in the directory now!

**Review by MuckT — APPROVED** [review]
Looks great with the mobile UI changes! 🚀

**Pull request merged**
