### PR TITLE
Submit my Dapp for the bakeoff

### PR DESCRIPTION
**Pull request by VelykyiP**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V2;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

For more information see the [Valora Listing Overview](https://docs.valora.xyz/listing/overview).

### CODE REVIEW

**Comment by MuckT** [comment]
I am unable to connect via connect to Valora via WalletConnect V2 on mobile.

**Comment by VelykyiP** [comment]
Hey Tom, thank you for the feedback. As I mentioned to Denisse, the bridge awaits the official announcement. Thus, the integration is currently available on the staging environment. I can share it privately with the Valora team before the official announcement is made.

**Comment by MuckT** [comment]
@VelykyiP would you be able to provide a url to test the integration on staging?

**Comment by MuckT** [comment]
@VelykyiP I am still unable to connect to Valora on mobile. I see it in the all options, but it's shown as disabled.

**Comment by VelykyiP** [comment]
Dear @MuckT, 

I looked into the issue with wallet selection. Could you please change the source chain to Celo (attaching the link for your convenience https://core.allbridge.io/?f=CEL&ft=USDT&t=ETH&tt=USDC)? The wallet selection screen that you shared displays the available wallets on the source chain (Ethereum). And since Valora is a Celo blockchain wallet, it is not on the list. 

Additionally, our bridge previously supported Valora via Wallet Connect on the desktop version. As of today, we introduced mobile browser support to make the bridging experience more convenient. Please let me know in case you encounter any issues.

**Comment by MuckT** [comment]
@VelykyiP Valora is now a multichain wallet supporting currently supporting Celo, Ethereum, Optimism and Arbitrum chains if you could make it possible to select Valora when using these chains that would be much appreciated.

**Review by MuckT — APPROVED** [review]

**Pull request merged**
