### PR TITLE
Add SpaceFi to Dapp list

### PR DESCRIPTION
**Pull request by SpaceFinance**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [ ] connects to Valora via WalletConnect V1 or DAppKit;
- [ ] must be mobile-first or mobile responsive;
- [ ] is in one of the existing categories; and
- [ ] includes a link to user documentation.

Please confirm you have:

- [ ] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [ ] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by SpaceFinance** [comment]
#87 failed to submit, I submitted it again, I hope it can be approved, thank you!

**Comment by jeanregisser** [comment]
Thanks for your submission! 🙌 

Does the project work with Celo mainnet? When I went to https://swap.spacefi.io/#/swap it asked me to switch to Celo Alfajores.
For the bakeoff we're only going to accept project that works on Celo mainnet.

**Comment by jeanregisser** [comment]
**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Comment by SpaceFinance** [comment]
Our project is still on the testnet and is expected to launch on the mainnet at the end of March. We may not be able to catch up with Bake Off, but we can integrate it into valora.

**Comment by jeanregisser** [comment]
Thanks! Yes, we'll only accept dapps that work on mainnet for the Bake Off.
Looking forward to include you in the Dapps page once you launch on mainnet.

**Comment by jeanregisser** [comment]
Hey, I see you were very close to making it 😯

Addressing our feedback by March 3rd @ 11:59 pm PST (UTC -8:00) was necessary to be part of the Bake Off.
Though you now don't qualify anymore as a Bake Off participant, I'm looking forward to including SpaceFi in the Valora's Dapps page as soon as the feedback is addressed.

Ping me when you want me to have a look again.

Thanks so much! 🙌 🙏

**Comment by SpaceFinance** [comment]
hi Jean,

Sorry for the late reply. We've fixed some bugs and will launch testnet2.0 soon. Before mainnet, I'll talk with you about cooperation. 

And welcome to join our testnet2.0: https://www.spacefi.io


Thanks,
SpaceFi

**Comment by silasbw** [comment]
Closing this, but feel free to address feedback or reach out with more questions if you're still interested in getting listed.

**Comment by SpaceFinance** [comment]
Thanks, fren. We’d like to list and will let you know before mainnet on CELO.

**Pull request closed without merging**
