### PR TITLE
Submitting Kolor for dapp listing

### PR DESCRIPTION
**Pull request by yieniggu**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by MuckT** [comment]
@yieniggu It looks like the assets size is 259 by 259 instead of 256 by 256 could you please adjust this in the PR. Also the only user documentation I am seeing is a link to a google doc from the terms and conditions on each sale, we might require that the documentation be included in the website itself, but I'll follow up with the results of the discussion. When attempting to connect via QR code from wallet connect the connection is successful; however, when attempting to connect from a mobile browser on my phone I am getting a connection timeout in Valora.

**Comment by MuckT** [comment]
@yieniggu after checking with the team about requirements.

The following are required:
- Terms and Conditions and user documentation should be present within the dapp.

Additional feedback on the existing documentation:
- What to expect after purchasing? 
- What actions KCCO owners can take? 
- How can the user verify that the land is being conserved?

**Comment by yieniggu** [comment]
Hey guys, thanks for pointing that out. Here are the answers from kolor team:

- ToCs are present now in dapp (not externally). Docs can be accessed from landing page: kolorapp.com or directly visited on docs.kolorapp.com
- Image size has been fixed.
- Regarding to Valora connection, this is something weird happening with Valora only. We're using rainbow kit and sometimes it let us grant access but get connection timeout, and sometimes we just get timeout on the access grant. We have communicated this to some members of Valora (including CEO) but we've only been provided with demos or examples to justify that error is not coming from Valora. (Important: we wont use another libraries apart from wagmi or anything provided from Celo as they are too restrictive to us rn).

Answering your specific questions:
**What to expect after purchasing?**
Lands purchased will begin generating yields in the form of Carbon Units that will be sell to our many providers in Chile or USA.

**What actions KCCO owners can take?**
KCCO can only execute decisions based on what the land DAOs define. (yes we have a snapshot-like dao decission making system built internally)

**How can the user verify that the land is being conserved?**
Kolor signs MOUs with every land owner for the next 30 years (at least) when kolor doesn't buy the land directly. If Kolor owns the land, it will be specified legally upon conditions and restrictions of chilean laws.

**Comment by yieniggu** [comment]
3 weeks since my last comment and no changes, any updates?

**Comment by silasbw** [comment]
For the Valora connection, I tried a few other wallets and got the same behavior @MuckT reports.  What other wallets have you tested with WC that work well?  That would be helpful for us to reproduce and debug.

**Comment by yieniggu** [comment]
We've now moved over to [celo officials rainbowkit package](https://github.com/celo-org/rainbowkit-celo). However we keep getting timeouts for now, hopefully this is fixed as we don't know where the error is coming from. We are also testing it in the [official demo of the package](https://rainbowkit-with-celo.vercel.app/) and getting same results. That should be everythin on our side, if this is not a problem from us it may be from Valora or Celo.


Will update once we get to connect to any of the dapps.

**Comment by silasbw** [comment]
OK, thanks for your patience.  We'll look closer and see if we can provide more debugging details in-app.

**Comment by yieniggu** [comment]
Hey guys, any updates regarding this? I just tried creating a new sample project using this libraries and got same results.

**Comment by silasbw** [comment]
Are you using WC2 or WC1?  It's worth noting that WC1 is deprecated and soon to be end of life.  If you're using WC1 can you try WC2?

**Comment by yieniggu** [comment]
Ok guys we just dropped official github libraries to handle connections and moved to a more standalone librarie. We've tested it and its working with WC and Valora, on mobile and through QR. Please let me know if you anything else from our side to be listed. As always thanks again for your help, time and feedback provided.

**Comment by silasbw** [comment]
Hey @yieniggu.  Thanks for drilling into the WC issues :100: .  We have a few more questions, and we thought it might be easier to chat about them, so I sent you a message on Discord.

**Comment by MuckT** [comment]
@yieniggu - hope you don't mind I had to make a few changes to the PR to get the test passing.

**Comment by MuckT** [comment]
@yieniggu when I tap terms and conditions I am getting the follow screen. Once that's fixed we should be good to merge!
Screen Shot 2023-03-03 at 12 18 17 PM

**Comment by yieniggu** [comment]
Issue has been fixed, you can now see toc when login with wallet

**Review by silasbw — APPROVED** [review]

**Comment by silasbw** [comment]
Just fix the merge conflicts @yieniggu .

**Comment by jeanregisser** [comment]
Hey @yieniggu we noticed https://dapp.kolorapp.com/ is down. Can you fix it?

**Pull request merged**
