### PR TITLE
Submitting Cred dApp for listing

### PR DESCRIPTION
**Pull request by kliskyjakub**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by MuckT** [comment]
@kliskyjakub looks like the assets sizing is off as it is 257 by 257 instead of 256 by 256. I was able to connect my wallet via QR code and sign the initial transaction.

**Comment by kliskyjakub** [comment]
@MuckT thanks for letting me know. The asset size should be correct now (256x256px)

**Comment by MuckT** [comment]
@kliskyjakub nit: The docs do not appear to include support contact links, but they are available in the footer on the main page of [credprotocol.com](http://credprotocol.com/). Would it be possible to include on https://app.credprotocol.com?

**Review by MuckT — APPROVED** [review]
LGTM!

**Pull request merged**
