### PR TITLE
add alities to Dapp list

### PR DESCRIPTION
**Pull request by WietzeSlagman**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by WietzeSlagman** [comment]
Currently the app is still running its POAP test-event instance on alities.io, we will be increasing app functionality by EOD. the version that will be displayed (with additional changes coming next week) can currently be found at [staging link alities](https://staging.alities.io)

On desktop --Frontpage is a bit weird with repeated content
- content updates are still planned, duplicate removed

On desktop --“Visit marketplace on mobile” link loads a QR code, unexpected
- button naming changed

-- Expected it to go to something like “[app.alities.io](http://app.alities.io/)” then allow me to connect my wallet
On mobile, after the onboarding screens one has to tap “skip” which immediately loads the permissions modal for the camera - expected another page, not a permissions modal
- button on desktop will move the user to the minting flow and artist profile upload

-- It does not load Valora, so this is buggy
Have to click an icon in the lower right to “connect with Valora”, which flashes a qr code but does load Valora
Then shows my Valora account budget and “Collected POAPs”
- if Valora has already been connected and given access in the current active session then a reconnect with valora will be instant

The icon on the left in the footer bar loads a blank page
- the QR scanner? if permissions are denied then a blank page is shown. In the next iteration this is changed and camera access can be reenabled

I'm not sure what to do next, all I see is I have no POAPs - what's next, what do I do with this dapp?
I am not able to find any user documentation.

**Comment by lisaw-valora** [comment]
Thank you! I had another look this morning.

**On Desktop, staging and not staging***

I was able to get logged in, but when I make an Artist Profile, it won't save.  Mint NFTs is greyed out. No docs

**On mobile, not staging**

Can do a lot more, very cool!!  All of the user-facing help docs have placeholder content.

**On mobile, staging**

* Totaly expected "Create your NFT" in the top right to be a button
* Was not able to make a connection between Valora and staging.alities.io to test further
* Still need user-facing docs

**Comment by WietzeSlagman** [comment]
Additional user documentation has been added to help guide the user on the platform.
Both on the desktop and on the mobile.

Still to add are the terms of use and privacy policy they will come before celo connect

**Comment by jeanregisser** [comment]
Thanks, could you check the "Allow edits by maintainers" box toward the bottom right side of the PR?
This is needed for the test to run so we can merge the PR 🙏 

Screenshot 2022-02-16 at 09 33 33

**Review by jeanregisser — APPROVED** [review]

**Comment by WietzeSlagman** [comment]
The option is missing from my PR, i think becaue i created the PR from an organisation. Do you know of a way to fix it or should i remake the pr from a personal fork?

**Comment by jeanregisser** [comment]
oh annoying, yes the best way is remaking the PR from a personal fork.
Do you mind doing this @WietzeSlagman?

**Comment by WietzeSlagman** [comment]
That is no problem I have created a PR from a personal fork see the PR here:
https://github.com/valora-inc/dapp-list/pull/160

the option is enabled as well

**Comment by jeanregisser** [comment]
Thanks, merged in #160

**Pull request closed without merging**
