### PR TITLE
Chimoney add unispend

### PR DESCRIPTION
**Pull request by Elozzy**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Review by MuckT — COMMENTED** [review]
Three changes needed:
1. The old asset for Chimoney should be removed.
2. The new asset should be the logo only.
3. The new asset should be 256 x 256 px.

**Comment by Elozzy** [comment]
@MuckT all request have been sorted out.

**Comment by MuckT** [comment]
@Elozzy looks the height on the `unispend.png` asset is 257 px instead of 256 px.

**Comment by Elozzy** [comment]
@MuckT  I've updated the asset

**Comment by MuckT** [comment]
@Elozzy it looks like some .DSstore files were incorrectly added to the PR. I'll make a new PR with these changes and close this one out once that is complete.

**Comment by MuckT** [comment]
Closing in favor of #395

**Pull request closed without merging**
