### PR TITLE
Submit awardool dapp for bakeoff

### PR DESCRIPTION
**Pull request by ruvnet**
> To make a submission for the Bake Off, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [ ] connects to Valora via WalletConnect V1 or DAppKit;
- [ ] must be mobile-first or mobile responsive;
- [ ] is in one of the existing categories; and
- [ ] includes a link to user documentation.

Please confirm you have:

- [ ] read the [Dapp Bake Off Information](https://valoraapp.com/bakeoff); and
- [ ] read the [Dapp Bake Off Rules](https://valoraapp.com/bakeoff-rules).

### CODE REVIEW

**Comment by jeanregisser** [comment]
Thanks for your submission! 🙌 

Here's the feedback:
1. Beside the initial WalletConnect session setup, where is Valora used for signing transactions?
2. the WalletConnect session icon specified (https://s3.amazonaws.com/appforest_uf/f1630541177271x320249793779692200/widget-greypink.svg) should be a png or jpeg as Valora doesn't support svg.

Could you please address this by Feb 28th? 🙏

**Comment by jeanregisser** [comment]
@ruvnet Gentle reminder, the deadline for addressing all feedback is today Feb 28th by end of day if you wanna participate in the Bake Off.
Let me know if you have any question.

**Comment by ruvnet** [comment]
each transaction is signed when exporting or purchasing NFTs

**Comment by ruvnet** [comment]
We uploaded a png 256x256 last week.

**Comment by jeanregisser** [comment]
Great, I'll take a look soon!

**_Update_**: we've extended the deadline for bake Off participants to address our feedback. The new deadline is **March 3rd @ 11:59 pm PST** (UTC -8:00).

**Comment by jeanregisser** [comment]
I took a new look but wasn't able to find a place where the WalletConnect session is used to sign transactions or messages with Valora.
Could you help me here?

**Comment by ruvnet** [comment]
Our platform is custodial, so the user sig is only required when exporting or sending crypto to purchase an NFT. The export will be released later this week, and the additional sig for sending crypto is likely to be next week. Sounds like your questions assume a non-custodial defi wallet / DAPP. Your bakeoff didn't mention the Dapp needed to be non-custodial.

**Comment by jeanregisser** [comment]
The dapp doesn't need to be non-custodial but it has to use Valora to send on-chain transactions or sign messages.
So far we haven't been able to see this with AwardPool.
Is there a place where this type of functionality is visible so we can test this?
We would be happy to include AwardPool if that's the case.

**Comment by jeanregisser** [comment]
Hey, I see you were very close to making it 😯

Addressing our feedback by March 3rd @ 11:59 pm PST (UTC -8:00) was necessary to be part of the Bake Off.
Though you now don't qualify anymore as a Bake Off participant, I'm looking forward to including AwardPool in the Valora's Dapps page as soon as the feedback is addressed.

Ping me when you want me to have a look again.

Thanks so much! 🙌 🙏

**Comment by silasbw** [comment]
Closing this, but feel free to address feedback or reach out with more questions if you're still interested in getting listed.

**Pull request closed without merging**
