### PR TITLE
Update valora-dapp-list.json to enable stCELO

### PR DESCRIPTION
**Pull request by product-matt**
> To make a submission to the Dapps Page, please complete the task lists
> below; otherwise remove them.

Your Dapp:

- [x] connects to Valora via WalletConnect V1 or DAppKit;
- [x] must be mobile-first or mobile responsive;
- [x] is in one of the existing categories; and
- [x] includes a link to user documentation.

### CODE REVIEW

**Comment by MuckT** [comment]
@product-matt would you please combine #231 into this PR so that all the changes an approvals can be in one PR.

**Comment by MuckT** [comment]
@product-matt once https://app.stcelo.xyz/ is live I am happy to re-review!

**Comment by product-matt** [comment]
all changes should now be ready in this single PR (2 commits)

**Comment by MuckT** [comment]
@product-matt it looks like we're missing a .png for this dapp also the currently link is serving a 404.

**Comment by product-matt** [comment]
added the .png. The link is serving a 404 because we launch this app publically tomorrow. However, valora has been given private access to the app (please check internally with Denise or Gus) so you can test the app. The same app will launch tomorrow publically under the mentioned URL of the PR

**Review by MuckT — APPROVED** [review]
@product-matt this looks great! I was able to stake and start unstaking without issue. There was a few times I had to manually refresh using an external browser, but that could be related to using an external browser: after a refresh all the balances were displayed correctly.

**Pull request merged**
