### PR TITLE
Yanda's Bake Off application

### PR DESCRIPTION
**Pull request by Yanda1**

### CODE REVIEW

**Comment by silasbw** [comment]
Thanks for the submission :raised_hands: !

Would you mind confirming the tasks in the PR template in this PR?  (https://github.com/valora-inc/dapp-list/blob/main/.github/PULL_REQUEST_TEMPLATE.md)

**Comment by jeanregisser** [comment]
Thanks so much! One other small thing, could you update the PNG to be 256x256? right now it's 270x270.
🙏

**Comment by aleksey-nov** [comment]
Hey Yanda team,
I was checking your submission, but it doesn't seem that your dapp connects to Valora. I tried using it from the iPhone in Safari, and taping on 'Connect wallet' button does nothing for me. Can you please fix it and submit your dapp again? Reminder, you should be using WalletConnect v 1.

**Comment by lisaw-valora** [comment]
Hi all!  It was challenging to find the user-facing docs since it seems one has to go back to the main URL to find them.  We'd like to see the docs linked from the app page - the footer could be an ideal spot.  

Also, once the docs are found, "Connect Wallet" has a very heavy focus on only Metamask. We'd like to see something about Valora there, or it's a dead-end for folks coming from Valora.

**Comment by jeanregisser** [comment]
@Yanda1 Gentle reminder, you need to address the feedback we left above by Feb 28th.
Let me know if you have any question.

**Comment by jeanregisser** [comment]
Update: we've extended the deadline for bake Off participants to address feedback to March 3rd @ 11:59 pm PST (UTC -8:00)

**Comment by jeanregisser** [comment]
Any update @Yanda1?

**Comment by jeanregisser** [comment]
Hey, I see you were very close to making it 😯

Addressing our feedback by March 3rd @ 11:59 pm PST (UTC -8:00) was necessary to be part of the Bake Off.
Though you now don't qualify anymore as a Bake Off participant, I'm looking forward to including Yanda in the Valora's Dapps page as soon as the feedback is addressed.

Ping me when you want me to have a look again.

Thanks so much! 🙌 🙏

**Comment by silasbw** [comment]
Closing this, but feel free to address feedback or reach out with more questions if you're still interested in getting listed.

**Pull request closed without merging**
