### PR TITLE
chore: removes celotracker for no walletconnect v2 support

### PR DESCRIPTION
**Pull request by MuckT**
### Description

Removes [Celo Tracker](https://celotracker.com/) for no WalletConnect v2 support.

### CODE REVIEW

**Comment by MuckT** [comment]
@gnardini Do you have plans to add Wallet Connect V2 support?

**Review by jeanregisser — APPROVED** [review]
Thanks! 👍

**Comment by gnardini** [comment]
> @gnardini Do you have plans to add Wallet Connect V2 support?

Sadly, no. I looked into it briefly but there are too many breaking changes in rainbowkit to make the update and I don't have the bandwidth for it.

If I ever resume active development for Celo Tracker I'll create a PR to re-add it to this list.

**Comment by jeanregisser** [comment]
Right makes sense, but in case it's useful, I think the [0.12.x](https://github.com/rainbow-me/rainbowkit/tree/0.12.x) branch of RainbowKit was updated for WC v2 too.
Because dapps couldn't just switch from ethers to viem.

Maybe could work as a stop gap solution without migration work.

**Comment by jeanregisser** [comment]
That's the path Mento took for now too: https://github.com/mento-protocol/mento-web/pull/69

**Pull request merged**
